# SPDX-FileCopyrightText: 2026 xfnw
#
# SPDX-License-Identifier: MIT

[package]
name = "fixed-hex"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository.workspace = true

[dependencies]
hybrid-array = "0.4.13"
typenum = { version = "1.20.1", features = ["const-generics"] }

[lints]
workspace = true
