# SPDX-FileCopyrightText: 2026 xfnw
#
# SPDX-License-Identifier: MIT

[package]
name = "fixed-hex"
description = "encoding and decoding hex with fixed-size arrays"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository.workspace = true

[dependencies]
hybrid-array = "0.4.13"
typenum = "1.20.1"

[lints]
workspace = true
