[package]
name = "vasm"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"

[dependencies]
argh = { version = "0.1.13", default-features = false, features = ["help"] }
foxerror = { version = "0.1.1", path = "../foxerror" }
nom = "8.0.0"

[lints]
workspace = true
