version = 1

[[annotations]]
path = "**"
SPDX-FileCopyrightText = "2025 xfnw"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = "tests/data/**"
SPDX-FileCopyrightText = "2025 xfnw"
SPDX-License-Identifier = "CC0-1.0"
