[package]
name = "foxerror"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "yet another proc macro for deriving Error on enums"
repository = "https://github.com/xfnw/workspace"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["derive"] }
