# SPDX-FileCopyrightText: 2025 xfnw
#
# SPDX-License-Identifier: MIT

[package]
name = "mark-tree"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository.workspace = true

[dependencies]

[lints]
workspace = true
